### PR TITLE
Meeting notes mar 3

### PR DESCRIPTION
**Pull request by WRose226**
# Team Rocket PR Template
## Description of Change Implemented
Meeting minutes & Software Dev Plan update
## Screenshots of it Working

### CODE REVIEW

**Review by iwatsukikevin — COMMENTED** [review]
Kevin Reviewed: Pushed back Design specifications document due date. Must finish flowchart with Gavin

**Comment by iwatsukikevin** [comment]
Added a review.

**Review by iwatsukikevin — APPROVED** [review]
Kevin's Review: Pushed back Design Specification Document due date. Need to finish flowchart with Gavin.

**Review by michael-mccain — APPROVED** [review]
Changes are in line with today's meeting.

**Pull request merged**
