### PR TITLE
Working

### PR DESCRIPTION
**Pull request by WRose226**
# Team Rocket PR Template
## Description of Change Implemented
Fixed Nick's compile errors, just had to rename the file to begin with uppercase letters, then fix the imports/exports.
This was something to do with the compiler not recognizing it as a proper js file...
## Screenshots of it Working
image

image

### CODE REVIEW

**Review by iwatsukikevin — COMMENTED** [review]
Looks good. 
So, localhost for beer tracker is 3000 instead of 8080?

**Review by Bruk04 — DISMISSED** [review]
Thanks, can't believe I overlooked that. Looks good.

**Review by Bruk04 — APPROVED** [review]
Now works. Approved.

**Review by michael-mccain — APPROVED** [review]
Much Improved!

**Pull request merged**
